name: printenv
on:
  push:

jobs:
  checkvaraiblechnag:
    runs-on: ubuntu-latest 
    steps:
  
      - uses: actions/checkout@v2

      - name: printenv
        run: |
          echo "${{ github.repository }}"
          echo "$GITHUB_RUN_ID"

